/*visualizing all basic combinations of controls and indep \ focal at each wave descriptively*/

libname anger 'C:\Users\solid\Google Drive\courses\PHD_2_Reading Course\data\clean';
ods graphics on / LOESSOBSMAX = 15000 ANTIALIASMAX=4500 ;
options FULLSTIMER threads cpucount=4 ;


data temp;
set anger.first;

run;
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_04 /  outline ;
                    loess y= anger_08 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= mastery_06 /  outline ;
                    loess y= anger_08 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_04 /  outline ;
                    loess y= anger_08 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_08 x= esteem_06 /  outline ;
                    loess y= anger_08 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_04 /  outline ;
                    loess y= anger_10 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= mastery_06 /  outline ;
                    loess y= anger_10 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_04 /  outline ;
                    loess y= anger_10 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_10 x= esteem_06 /  outline ;
                    loess y= anger_10 x= esteem_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_04 /  outline ;
                    loess y= anger_12 x= mastery_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= mastery_06 /  outline ;
                    loess y= anger_12 x= mastery_06 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_04 /  outline ;
                    loess y= anger_12 x= esteem_04 / group= race  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= r_age_fw  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= female  NOMARKERS; run; 
proc sgplot data=temp;
                    heatmap y= anger_12 x= esteem_06 /  outline ;
                    loess y= anger_12 x= esteem_06 / group= race  NOMARKERS; run; 